import { ProofInterface } from "./proof.interface";
import { SubjectInterface } from "./subject.interface";
import { UserInterface } from "./user.interface";


// Generated by https://quicktype.io

export interface AbsenceExtraInfoInterface {
    _id:                string;
    absenceDate:        string;
    absenceDescription: string;
    proof:              ProofInterface;
    subject:            SubjectInterface;
    user:               UserInterface;
    __v:                number;
}