// Generated by https://quicktype.io

export interface AbsenceInterface {
    _id:                string;
    absenceDate:        string;
    absenceDescription: string;
    proof:              string;
    subject:            string;
    user:               string;
    __v:                number;
}
