// Generated by https://quicktype.io

export interface CreateAbsenceInterface {
    absenceDate:        string;
    absenceDescription: string;
    proof:              string;
    subject:            string;
    user:               string;
}
