// Generated by https://quicktype.io

export interface UserInterface {
    _id:      string;
    name:     string;
    lastName: string;
    dni:      number;
    role:     string;
    __v:      number;
}
