// Generated by https://quicktype.io

export default interface UserInterface {
    _id:       string;
    name:      string;
    lastName:  string;
    dni:       number;
    role:      string;
    __v:       number;
    password?: string;
}